apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "Message": "Hello world!"
    }
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 75c40364-8e73-4309-a260-bfa6eec7e158
    keyvaultName: fergab22
    objects:  |
      array:
        - |
          objectName: TestSecret
          objectType: secret
    tenantId: 6f695966-8106-48a2-a786-cd55ab5d935d
  secretObjects:
  - secretName: my-key-ring
    type: Opaque
    data:
    - key: testSecret
      objectName: TestSecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  selector:
    matchLabels:
      app: my-api
  replicas: 1
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: fergab22.azurecr.io/myapi:1.1
        ports:
          - containerPort: 80
        env:
        - name: TEST_SECRET
          valueFrom:
            secretKeyRef:
              name: my-key-ring
              key: testSecret
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/config
        - name: secrets-store01
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: appsettings-volume
        configMap:
          name: my-app-config
      - name: secrets-store01
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: my-api
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-api-service
              port:
                number: 8080
